[project]
name = "TargetVison"
version = "0.1.0"
description = "An app for detecting and scoring arrows on a 40cm FITA target face from images"
authors = [{ name = "Den", email = "ulyanovdenis@gmail.com" }]
license = { text = "MIT" }
dependencies = [
    "opencv-python",    # For image processing
    "numpy",            # Numerical operations
    "scipy",            # Advanced image transformations
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.black]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--disable-warnings"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
